### PR TITLE
feat/github action

### PR DESCRIPTION
**Pull request by PaperHS**
- feat: add github action
- bump version

### CODE REVIEW

**Comment by wangshijun** [comment]
### Code Coverage
|File|Coverage [0%]|:x:|
|:-|:-:|:-:|
|[ArrayUtils.java](https://github.com/ArcBlock/did-wallet-sdk-android/blob/b6a4b95b330f970b071d34b9c0db627aef4e02e5/wallet-sdk%2Fsrc%2Fmain%2Fjava%2Fio%2Farcblock%2Fwalletkit%2Futils%2FArrayUtils.java)|0%|:x:|

|Total Project Coverage|0%|:x:|
|:-|:-:|:-:|

**Comment by wangshijun** [comment]
### Code Coverage
|File|Coverage [12%]|:x:|
|:-|:-:|:-:|
|[ArrayUtils.java](https://github.com/ArcBlock/did-wallet-sdk-android/blob/c1d6093b1679e2a9bc48a0084bcdfa7833e3a5d6/wallet-sdk%2Fsrc%2Fmain%2Fjava%2Fio%2Farcblock%2Fwalletkit%2Futils%2FArrayUtils.java)|12%|:x:|

|Total Project Coverage|47.91%|:green_apple:|
|:-|:-:|:-:|

**Comment by wangshijun** [comment]
### Code Coverage
|File|Coverage [96%]|:green_apple:|
|:-|:-:|:-:|
|[ArrayUtils.java](https://github.com/ArcBlock/did-wallet-sdk-android/blob/ef70d6a07d0c35381f47824a0f3996e605911c19/wallet-sdk%2Fsrc%2Fmain%2Fjava%2Fio%2Farcblock%2Fwalletkit%2Futils%2FArrayUtils.java)|96%|:green_apple:|

|Total Project Coverage|48.55%|:green_apple:|
|:-|:-:|:-:|

**Comment by wangshijun** [comment]
### Code Coverage
|File|Coverage [96%]|:green_apple:|
|:-|:-:|:-:|
|[ArrayUtils.java](https://github.com/ArcBlock/did-wallet-sdk-android/blob/2e2154fc265a78aaa0ede338d29d33310159308c/wallet-sdk%2Fsrc%2Fmain%2Fjava%2Fio%2Farcblock%2Fwalletkit%2Futils%2FArrayUtils.java)|96%|:green_apple:|

|Total Project Coverage|48.55%|:green_apple:|
|:-|:-:|:-:|

**Review by NateRobinson — APPROVED** [review]
LGTM

**Pull request merged**
